name: Cập nhật images.json

on:
  push:
    paths:
      - 'images/**'

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Tạo images.json có ngày upload
        run: |
          cd images
          echo "[" > images.json
          for file in *.{jpg,jpeg,png,gif,webp}; do
            [ -f "$file" ] || continue
            date=$(git log -1 --format="%cs" -- "$file" || date +"%Y-%m-%d")
            echo "  {\"file\": \"$file\", \"date\": \"$date\"}," >> images.json
          done
          # Xóa dấu phẩy cuối cùng
          sed -i '$ s/,$//' images.json
          echo "]" >> images.json

      - name: Commit và push images.json
        run: |
          cd $GITHUB_WORKSPACE
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add images/images.json
          # commit nếu có thay đổi, tránh exit code 128
          if git diff-index --quiet HEAD; then
            echo "Không có gì để commit"
          else
            git commit -m "Tự động cập nhật images.json"
            git push
          fi
